// Generated by https://quicktype.io

export interface IHours {
  id:                   number;
  name:                 string;
  surname:              string;
  date:                 string;
  single_hours:         number | null;
  group_hours:          number | null;
  pay_rate_single:      number;
  pay_rate_group:       number;
}
