// Generated by https://quicktype.io

export interface IInstructorPagingResponse {
  count:    number;
  next:     string;
  previous: string;
  results:  Result[];
}

export interface IInstructorDetailResponse {
  id:               number;
  name:             string;
  surname:          string;
  nickname:         null | string;
  mobile_number:    null | string;
  birth_date:       string;
  email_address:    string;
  weight:           number;
  available_from:   null | string;
  available_to:     null | string;
  iko_id:           number;
  iko_level:        string;
  pay_rate_single:  number | null;
  pay_rate_group:  number | null;
  english_lessons:  boolean | null;
  kids_lessons:     boolean | null;
  group_lessons:    boolean;
  daily_hour_limit: number | null;
  active:           boolean;
}

export interface Result {
  id:               number;
  name:             string;
  surname:          string;
  nickname:         null | string;
  mobile_number:    null | string;
  birth_date:       string;
  email_address:    string;
  weight:           number;
  available_from:   null | string;
  available_to:     null | string;
  iko_id:           number;
  iko_level:        string;
  pay_rate_single:  number | null;
  pay_rate_group:  number | null;
  english_lessons:  boolean | null;
  kids_lessons:     boolean | null;
  group_lessons:    boolean | null;
  daily_hour_limit: number | null;
  active:           boolean;
}


