// Generated by https://quicktype.io

import { Time } from '@angular/common';

export interface ILessonPagingResponse {
  count:    number;
  next:     string;
  previous: string;
  results:  Result[];
}

export interface ILessonDetailResponse {
  id:           number;
  created_date: string;
  date:         string;
  time:         Time;
  student:      Student[];
  instructor:   Instructor[];
  duration:     number;
  equipment:    string;
  kite_brand:   null | string;
  kite_size:    number | null;
  board:        null | string;
  paid:         boolean;
  status:       null | string;
  comment:      null | string;
  in_progress:   null | boolean;
}

export interface Result {
  id:           number;
  created_date: string;
  date:         string;
  time:         Time;
  student:      Student[];
  instructor:   Instructor[];
  duration:     number;
  equipment:    string;
  kite_brand:   null | string;
  kite_size:    number | null;
  board:        null | string;
  paid:         boolean;
  status:       null | string;
  comment:      null | string;
  in_progress:   null | boolean;
}

export interface Instructor {
  id:               number;
  name:             string;
  surname:          string;
  nickname:         string;
  mobile_number:    string;
  birth_date:       string;
  weight:           number;
  available_from:   string;
  available_to:     string;
  iko_level:        string;
  pay_rate:         number;
  english_lessons:  boolean;
  kids_lessons:     boolean;
  group_lessons:    boolean;
  daily_hour_limit: number;
  active:           boolean;
}

export interface Student {
  id:            number;
  name:          string;
  surname:       string;
  birth_date:    string;
  email_address: string;
  mobile_number: string;
  weight:        number;
  stay_location: string;
  iko_level:     string;
  arrival_date:  Date;
  leave_date:    Date;
  comment:       string;
  register_date: string;
}
