// Generated by https://quicktype.io

export interface IStudentPagingResponse {
  count:    number;
  next:     string;
  previous: string;
  results:  Result[];
}

export interface IStudentDetailResponse {
  id?:            number;
  name:          string;
  surname:       string;
  birth_date:    string;
  email_address: string;
  mobile_number: string;
  weight:        number;
  wetsuit_size:  string;
  harness_size:  string;
  stay_location: string;
  iko_id:        number;
  iko_level:     string;
  arrival_date:  string;
  leave_date:    string;
  comment:       string;
  register_date?: string;
}

export interface Result {
  id:            number;
  name:          string;
  surname:       string;
  birth_date:    string;
  email_address: string;
  mobile_number: string;
  weight:        number;
  wetsuit_size:  string;
  harness_size:  string;
  stay_location: string;
  iko_id:        number;
  iko_level:     string;
  arrival_date:  string;
  leave_date:    string;
  comment:       string;
  register_date: string;
}
